dateRun: DateDemo.o DateClass.o
	g++ -o dateRun DateDemo.o DateClass.o

DateDemo.o: DateDemo.cpp Date.h
	g++ -c -o DateDemo.o DateDemo.cpp Date.h

DateClass.o: DateClass.cpp Date.h
	g++ -c -o DateClass.o DateClass.cpp Date.h
